# Generated by Django 5.2.15 on 2026-06-15 08:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ValidationResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=100, unique=True)),
                ('n_essays', models.IntegerField()),
                ('pearson_r', models.FloatField(blank=True, null=True)),
                ('spearman_rho', models.FloatField(blank=True, null=True)),
                ('qwk', models.FloatField(blank=True, null=True)),
                ('bias_mean', models.FloatField(blank=True, null=True)),
                ('loa_upper', models.FloatField(blank=True, null=True)),
                ('loa_lower', models.FloatField(blank=True, null=True)),
                ('rf_r2', models.FloatField(blank=True, null=True)),
                ('gb_r2', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'validation_results',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Essay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(blank=True, max_length=50, null=True)),
                ('source', models.CharField(choices=[('persuade', 'PERSUADE Dataset'), ('manual', 'Manual Upload')], default='persuade', max_length=50)),
                ('prompt_id', models.IntegerField(blank=True, null=True)),
                ('essay_text', models.TextField()),
                ('word_count', models.IntegerField(default=0)),
                ('language', models.CharField(default='en', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'essays',
                'indexes': [models.Index(fields=['source'], name='essays_source_77485a_idx'), models.Index(fields=['prompt_id'], name='essays_prompt__69df4d_idx')],
            },
        ),
        migrations.CreateModel(
            name='ExpertScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score_raw', models.FloatField()),
                ('score_normalized', models.FloatField()),
                ('score_arg', models.IntegerField(blank=True, null=True)),
                ('score_evidence', models.IntegerField(blank=True, null=True)),
                ('score_logic', models.IntegerField(blank=True, null=True)),
                ('score_perspective', models.IntegerField(blank=True, null=True)),
                ('score_metacog', models.IntegerField(blank=True, null=True)),
                ('source', models.CharField(choices=[('persuade_holistic', 'PERSUADE Holistic Score'), ('manual', 'Manual Expert Annotation')], max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='expert_score', to='assessment.essay')),
            ],
            options={
                'db_table': 'expert_scores',
            },
        ),
        migrations.CreateModel(
            name='LLMScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(blank=True, max_length=100, null=True)),
                ('model_name', models.CharField(default='gptoss-120b', max_length=100)),
                ('score_arg', models.IntegerField(blank=True, null=True)),
                ('score_evidence', models.IntegerField(blank=True, null=True)),
                ('score_logic', models.IntegerField(blank=True, null=True)),
                ('score_perspective', models.IntegerField(blank=True, null=True)),
                ('score_metacog', models.IntegerField(blank=True, null=True)),
                ('score_composite', models.FloatField(blank=True, null=True)),
                ('reasoning', models.TextField(blank=True, null=True)),
                ('arg_structure', models.JSONField(blank=True, null=True)),
                ('detected_fallacies', models.JSONField(blank=True, null=True)),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_score', to='assessment.essay')),
            ],
            options={
                'db_table': 'llm_scores',
            },
        ),
        migrations.CreateModel(
            name='LLMFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_text', models.TextField()),
                ('weakest_dimension', models.CharField(blank=True, max_length=50, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='llm_feedback', to='assessment.essay')),
                ('llm_score', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='assessment.llmscore')),
            ],
            options={
                'db_table': 'llm_feedback',
            },
        ),
        migrations.CreateModel(
            name='NLPFeatures',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arg_claim_count', models.IntegerField(default=0)),
                ('arg_evidence_count', models.IntegerField(default=0)),
                ('arg_warrant_count', models.IntegerField(default=0)),
                ('arg_counter_count', models.IntegerField(default=0)),
                ('arg_coverage', models.FloatField(default=0)),
                ('fallacy_total', models.IntegerField(default=0)),
                ('fallacy_authority', models.IntegerField(default=0)),
                ('fallacy_generalize', models.IntegerField(default=0)),
                ('fallacy_dichotomy', models.IntegerField(default=0)),
                ('fallacy_circular', models.IntegerField(default=0)),
                ('sentence_count', models.IntegerField(default=0)),
                ('avg_sent_length', models.FloatField(default=0)),
                ('transition_density', models.FloatField(default=0)),
                ('type_token_ratio', models.FloatField(default=0)),
                ('subordination_idx', models.FloatField(default=0)),
                ('metacognitive_count', models.IntegerField(default=0)),
                ('has_counter_arg', models.BooleanField(default=False)),
                ('aqi', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('essay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='nlp_features', to='assessment.essay')),
            ],
            options={
                'db_table': 'nlp_features',
            },
        ),
    ]
